### ISSUE TITLE
[BUG] RazorEngine cannot resolve assembly references

### ISSUE THREAD

**Issue by Sharp0802** [Sharp0802/blogman#4]
**What is problem** 

`RazorEngine.NetCore` cannot resolve assembly references.
Actually, `RazorEngine.NetCore` is not trimming-compatible.
Thus, To use `RazorEngine.NetCore` with trimming,
Custom assembly reference resolver required.

https://antaris.github.io/RazorEngine/ReferenceResolver.html

**How to reproduce**

1. Run `blogman build` on already initialized project with some posts.
2. Error occurs

**Comment by Sharp0802** [comment]
Runtime cannot resolve reference.
Below is exception message:

```
Unhandled exception. System.TypeLoadException: Method 'get_SyncRoot' in type 'System.Collections.Generic.Stack`1' from assembly 'System.Collections, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' does not have an implementation.
   at System.TermInfo.ParameterizedStrings.Evaluate(String, FormatParam[] )
   at System.TermInfo.ParameterizedStrings.Evaluate(String, FormatParam)
   at System.ConsolePal.WriteSetColorString(Boolean, ConsoleColor)
   at System.ConsolePal.RefreshColors(ConsoleColor&, ConsoleColor)
   at System.ConsolePal.set_ForegroundColor(ConsoleColor)
   at System.Console.set_ForegroundColor(ConsoleColor)
   at System.CommandLine.IO.ConsoleExtensions.SetTerminalForegroundRed(IConsole)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<UseExceptionHandler>g__Default|1(Exception, InvocationContext)
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.<InvokeAsync>g__FullInvocationChainAsync|2_0(InvocationContext)
   at System.CommandLine.CommandExtensions.InvokeAsync(Command, String[], IConsole )
   at Program.<Main>$(String[]) in /home/sharp0802/repos/src/BlogMan/src/BlogMan/Program.cs:line 6
   at Program.<Main>(String[])
Aborted (core dumped)
```

**Comment by Sharp0802** [comment]
Referenced libraries(RazorEngine, YamlDotNet) seems not to support assembly trimming at all.
Thus, It's necessary to disable assembly trimming.
